### ISSUE TITLE
Plugin.txt formatting Error

### ISSUE THREAD

**Issue by HydroChromatic** [UtaUtaUtau/nnsvslabeling#1]
plugin.txt's formatting is odd and causes there to be no spacing between "Label to UST" and "execute" so utau's drop down menu for plugins read as "Label to USTexecute" and does not execute instead of reading as "Label to UST" and executing. 

rewriting the plugin.txt fixes the error but some (like me) may not catch it at first

**Comment by ghost** [comment]
I ran into this and it appears that the plugin.txt is in Unix EOL (\n) instead of Windows EOL (\r\n) format.
changing this fixes the issue.
[plugin.txt](https://github.com/UtaUtaUtau/nnsvslabeling/files/7222386/plugin.txt)

**Comment by UtaUtaUtau** [comment]
The issue was that GitHub converted all my CRLF to LF, but I found out how to fix that now.
