### ISSUE TITLE
Japanese language detection is inaccurate

### ISSUE THREAD

**Issue by ghost** [UtaUtaUtau/nnsvslabeling#2]
Japanese datasets are incorrectly detected as another language if capitalized phonemes exist.
For NNSVS Japanese datasets (and Japanese speech datasets in general, somewhat), capitalized vowel phonemes represent unvoiced vowels.

May I suggest updating the detection?
<details>
  <summary>I don't know python so I replaced your detection with this out of desperation. </summary>
<p>
In case someone comes along before this issue is resolved and needs a quick 'fix'.

```python
    label_lang = input('Is dataset Japanese? [y/n] ')
    if label_lang.lower() == 'y':
        jpn = True
    else:
        jpn = False
```

</p>
</details>

May I also suggest adding the capitalized phonemes to the vowel list and change line 129 to something like `not in ('pau', 'sil') else 'R'` since pau and sil are used interchangeably?

Thank you.

**Comment by UtaUtaUtau** [comment]
Sorry again for the crude fix! I added more to the README on why Japanese is separated.
